modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="hedgehog"
version="${file.jarVersion}"
displayName="Hedgehog"
displayURL = "https://discord.gg/5wp2d6xeFW"
authors = "Orcinus"
logoFile="hedgehog_logo.png"
description='''
This mod adds hedgehog to the base game

Special Thanks:

- Ninni (Visual Artist)
- Wolf (Logo Artist)

'''
[[dependencies.hedgehog]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hedgehog]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
